version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel --token $VERCEL_TOKEN --prod=false --confirm

workflows:
  deploy_on_pr:
    jobs:
      - deploy